[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.17.0"

# Allow embedding on Webflow (staging + Designer) and NTRO domains
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self' https://*.webflow.io https://*.webflow.com https://ntro.org.au https://www.ntro.org.au"
